import os
import json

def generate_notebook():
    notebook_path = os.path.join(
        "D:\\", "ananda_personal", "my_project", "Chatbot_YuedPao",
        "notebooks", "intent_rank", "compare_editdistance_vs_pure_bert.ipynb"
    )
    os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
    
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🧪 Experiment Benchmark: Pure BERT vs. Edit Distance + BERT (Fair 5-Fold CV)\n",
                "\n",
                "สมุดโน้ตเล่มนี้ได้รับการปรับปรุงเพื่อ **แก้ไขปัญหา Data Leakage** และทำการวัดผลเชิงวิทยาศาสตร์อย่างถูกต้องเที่ยงตรงด้วย **5-Fold Stratified Cross-Validation**\n",
                "\n",
                "---\n",
                "\n",
                "### 🔬 5 วิธีที่นำมาทดสอบเปรียบเทียบ (Evaluation Methods):\n",
                "1. **Method 1: Pure BERT (`intfloat/multilingual-e5-small`)**\n",
                "   - ส่งข้อความดั้งเดิม (`raw_query`) ตรงเข้า BERT โดย **ไม่ผ่าน** Edit Distance หรือ Rule ใดๆ\n",
                "2. **Method 2: Edit Distance + BERT**\n",
                "   - ทำการแก้คำผิดด้วย Domain Vocab Edit Distance (Tier 0) ก่อนส่งเข้า BERT\n",
                "3. **Method 3: Tier 1 Priority Rules + Pure BERT**\n",
                "   - ใช้ Priority Rules กรองคีย์เวิร์ดเด่นก่อน (งบ/ราคา/สเปค) แล้วเคสเปิดส่งเข้า Pure BERT\n",
                "4. **Method 4a: 4-Tier Pipeline (No Few-Shot)**\n",
                "   - สถาปัตยกรรม (Tier 0 Spell Fix + Tier 1 Rules + Tier 3 BERT Fallback) โดยข้าม ChromaDB Few-Shot\n",
                "5. **Method 4b: Full 4-Tier Pipeline (With Leak-Free 5-Fold CV Few-Shot)**\n",
                "   - สถาปัตยกรรม 4-Tier ครบชุด โดยสร้าง ChromaDB Few-Shot Index จาก Train Fold (80%) เท่านั้น และทดสอบบน Test Fold (20%) เพื่อการวัดผลที่ปราศจาก Data Leakage 100%\n",
                "\n",
                "---\n",
                "📌 **คำแนะนำ:** สามารถเปิดสมุดโน้ตนี้ใน Jupyter / VS Code แล้วสั่ง **Run All Cells** เพื่อรันการประมวลผล 5-Fold CV และดูตารางสรุปผลได้ทันทีครับ"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🛠️ Step 1: โหลดไลบรารี ชุดข้อมูล Ground Truth และ Model Warmup"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import sys\n",
                "import os\n",
                "import json\n",
                "import time\n",
                "import re\n",
                "from typing import Dict, List, Any, Tuple\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import chromadb\n",
                "from sentence_transformers import SentenceTransformer, util\n",
                "from sklearn.metrics import accuracy_score, f1_score\n",
                "from sklearn.model_selection import StratifiedKFold\n",
                "\n",
                "# ตั้งค่า Encoding Safeguard สำหรับ Windows CLI (Guard สำหรับ Jupyter OutStream)\n",
                "if hasattr(sys.stdout, 'reconfigure'):\n",
                "    sys.stdout.reconfigure(encoding='utf-8')\n",
                "\n",
                "# ระบุ Path ไปยัง Root Project\n",
                "project_root = os.path.abspath(os.path.join(os.getcwd(), \"..\", \"..\"))\n",
                "if project_root not in sys.path:\n",
                "    sys.path.insert(0, project_root)\n",
                "\n",
                "from app.services.intent_service import IntentService\n",
                "\n",
                "# 1. โหลด Ground Truth Dataset (136 ตัวอย่าง)\n",
                "gt_path = os.path.join(project_root, \"app\", \"data\", \"nlp_ground_truth.json\")\n",
                "with open(gt_path, \"r\", encoding=\"utf-8\") as f:\n",
                "    ground_truth_data = json.load(f)\n",
                "\n",
                "print(f\"✅ โหลด nlp_ground_truth.json สำเร็จ! จำนวนทั้งหมด {len(ground_truth_data)} ตัวอย่าง\")\n",
                "typo_count = sum(1 for item in ground_truth_data if item.get('has_typos', False))\n",
                "clean_count = len(ground_truth_data) - typo_count\n",
                "print(f\"   - ข้อความที่มีคำพิมพ์ผิด (Typo Queries): {typo_count} ประโยค\")\n",
                "print(f\"   - ข้อความสะกดถูกต้อง (Clean Queries): {clean_count} ประโยค\")\n",
                "\n",
                "# 2. โหลดโมเดล BERT (intfloat/multilingual-e5-small)\n",
                "print(\"⏳ กำลังโหลดโมเดล BERT: intfloat/multilingual-e5-small...\")\n",
                "bert_model = SentenceTransformer('intfloat/multilingual-e5-small')\n",
                "print(\"✅ โหลดโมเดล BERT สำเร็จ!\")\n",
                "\n",
                "# 3. Model Warmup (ยิงประโยคดัมมี่เพื่อเคลียร์ Overhead และ First-call Latency)\n",
                "dummy_warmup = bert_model.encode([\"query: Warmup inference sentence\"], convert_to_tensor=True)\n",
                "print(\"🔥 Model Warmup สำเร็จพร้อมสำหรับวัด Latency เที่ยงตรง!\")\n",
                "\n",
                "# 4. เริ่มต้น IntentService ตัวแม่\n",
                "intent_service = IntentService(data_dir=os.path.join(project_root, \"app\", \"data\"))\n",
                "print(\"✅ เริ่มต้น IntentService สำเร็จ!\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📐 Step 2: นิยาม Intent Passages & Reference Embeddings"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "INTENT_PASSAGES = {\n",
                "    \"product_search\": \"passage: ซื้อเสื้อ หาเสื้อ ขอดูเสื้อ สั่งซื้อเสื้อผ้า เสื้อยืด กางเกง เสื้อโปโล เสื้อเชิ้ต ราคาสินค้า สี ไซส์ ทรงเสื้อ มีงบ มีราคา ไม่เกิน\",\n",
                "    \"size_recommendation\": \"passage: สอบถามไซส์ แนะนำไซส์เสื้อ ขนาดเสื้อ รอบอก สัดส่วนความสูงและน้ำหนัก ไซส์ไหนดี ใส่ไซส์อะไร เหมาะกับไซส์อะไร\",\n",
                "    \"fabric_comparison\": \"passage: สอบถามเนื้อผ้า เปรียบเทียบคุณสมบัติผ้า ผ้าต่างกันยังไง ซักแล้วยับไหม ผ้านุ่ม ระบายอากาศ ดีกว่ายังไง คุณสมบัติของผ้า\",\n",
                "    \"promotion_discount\": \"passage: โปรโมชัน ดีลพิเศษ ประจำวัน ประจำเดือน แฟลชเซล ส่วนลด คูปอง ลดราคา วันนี้ เดือนนี้ ส่งฟรี\"\n",
                "}\n",
                "intent_classes = list(INTENT_PASSAGES.keys())\n",
                "passage_embeddings = bert_model.encode(list(INTENT_PASSAGES.values()), convert_to_tensor=True)\n",
                "print(f\"✅ คำนวณ Passage Embeddings สำหรับ {len(intent_classes)} Intent เรียบร้อยแล้ว\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 Step 3: นิยามฟังก์ชันทำนายผลทั้ง 5 สถาปัตยกรรม"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Method 1: Pure BERT (ส่ง raw query ตรงเข้า BERT) ---\n",
                "def predict_method_1_pure_bert(raw_query: str) -> Tuple[str, float]:\n",
                "    start_t = time.perf_counter()\n",
                "    query_text = f\"query: {raw_query}\"\n",
                "    query_embedding = bert_model.encode(query_text, convert_to_tensor=True)\n",
                "    scores = util.cos_sim(query_embedding, passage_embeddings)[0]\n",
                "    best_idx = int(scores.argmax())\n",
                "    latency = (time.perf_counter() - start_t) * 1000.0\n",
                "    return intent_classes[best_idx], latency\n",
                "\n",
                "# --- Method 2: Edit Distance + BERT (ผ่าน Tier 0 แก้คำผิดก่อนเข้า BERT) ---\n",
                "def predict_method_2_editdistance_bert(raw_query: str) -> Tuple[str, float]:\n",
                "    start_t = time.perf_counter()\n",
                "    corrected_query, _ = intent_service.correct_spelling(raw_query)\n",
                "    query_text = f\"query: {corrected_query}\"\n",
                "    query_embedding = bert_model.encode(query_text, convert_to_tensor=True)\n",
                "    scores = util.cos_sim(query_embedding, passage_embeddings)[0]\n",
                "    best_idx = int(scores.argmax())\n",
                "    latency = (time.perf_counter() - start_t) * 1000.0\n",
                "    return intent_classes[best_idx], latency\n",
                "\n",
                "# --- Method 3: Tier 1 Priority Rules + Pure BERT ---\n",
                "def predict_method_3_rules_pure_bert(raw_query: str) -> Tuple[str, float]:\n",
                "    start_t = time.perf_counter()\n",
                "    raw_lower = raw_query.lower()\n",
                "    \n",
                "    if (re.search(r'(?:สูง|หนัก)\\s*\\d+', raw_lower) or re.search(r'(?:ไซส์|ขนาด)(?:อะไร|ไหน|เท่าไหร่|ดี)', raw_lower)) and not re.search(r'(?:ไม่เกิน|งบ|ราคา|บาท)', raw_lower):\n",
                "        return \"size_recommendation\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(ft in raw_lower for ft in [\"ต่างกันยังไง\", \"ต่างกับ\", \"ดีกว่ายังไง\", \"คุณสมบัติ\", \"ผ้านุ่ม\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"fabric_comparison\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"โปรโมชัน\", \"โปรโมชั่น\", \"ส่วนลด\", \"คูปอง\", \"แฟลชเซล\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"promotion_discount\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"ไม่เกิน\", \"งบ\", \"บาท\", \"ขอดู\", \"หาเสื้อ\", \"ราคาประมาณ\"]):\n",
                "        return \"product_search\", (time.perf_counter() - start_t) * 1000.0\n",
                "        \n",
                "    query_text = f\"query: {raw_query}\"\n",
                "    query_embedding = bert_model.encode(query_text, convert_to_tensor=True)\n",
                "    scores = util.cos_sim(query_embedding, passage_embeddings)[0]\n",
                "    best_idx = int(scores.argmax())\n",
                "    latency = (time.perf_counter() - start_t) * 1000.0\n",
                "    return intent_classes[best_idx], latency\n",
                "\n",
                "# --- Method 4a: 4-Tier Pipeline (No Few-Shot Lookup) ---\n",
                "def predict_method_4a_no_fewshot(raw_query: str) -> Tuple[str, float]:\n",
                "    start_t = time.perf_counter()\n",
                "    corrected_query, _ = intent_service.correct_spelling(raw_query)\n",
                "    raw_lower = raw_query.lower()\n",
                "    \n",
                "    # Tier 1 Priority Rules\n",
                "    if (re.search(r'(?:สูง|หนัก)\\s*\\d+', raw_lower) or re.search(r'(?:ไซส์|ขนาด)(?:อะไร|ไหน|เท่าไหร่|ดี)', raw_lower)) and not re.search(r'(?:ไม่เกิน|งบ|ราคา|บาท)', raw_lower):\n",
                "        return \"size_recommendation\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(ft in raw_lower for ft in [\"ต่างกันยังไง\", \"ต่างกับ\", \"ดีกว่ายังไง\", \"คุณสมบัติ\", \"ผ้านุ่ม\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"fabric_comparison\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"โปรโมชัน\", \"โปรโมชั่น\", \"ส่วนลด\", \"คูปอง\", \"แฟลชเซล\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"promotion_discount\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"ไม่เกิน\", \"งบ\", \"บาท\", \"ขอดู\", \"หาเสื้อ\", \"ราคาประมาณ\"]):\n",
                "        return \"product_search\", (time.perf_counter() - start_t) * 1000.0\n",
                "        \n",
                "    # Tier 3 BERT Passage Match (Skip Tier 2.5 Few-Shot)\n",
                "    query_text = f\"query: {corrected_query}\"\n",
                "    query_embedding = bert_model.encode(query_text, convert_to_tensor=True)\n",
                "    scores = util.cos_sim(query_embedding, passage_embeddings)[0]\n",
                "    best_idx = int(scores.argmax())\n",
                "    latency = (time.perf_counter() - start_t) * 1000.0\n",
                "    return intent_classes[best_idx], latency\n",
                "\n",
                "# --- Method 4b: Full 4-Tier Pipeline (With Leak-Free Few-Shot Collection) ---\n",
                "def predict_method_4b_cv_fewshot(raw_query: str, cv_chroma_collection) -> Tuple[str, float]:\n",
                "    start_t = time.perf_counter()\n",
                "    corrected_query, _ = intent_service.correct_spelling(raw_query)\n",
                "    raw_lower = raw_query.lower()\n",
                "    \n",
                "    # Tier 1 Priority Rules\n",
                "    if (re.search(r'(?:สูง|หนัก)\\s*\\d+', raw_lower) or re.search(r'(?:ไซส์|ขนาด)(?:อะไร|ไหน|เท่าไหร่|ดี)', raw_lower)) and not re.search(r'(?:ไม่เกิน|งบ|ราคา|บาท)', raw_lower):\n",
                "        return \"size_recommendation\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(ft in raw_lower for ft in [\"ต่างกันยังไง\", \"ต่างกับ\", \"ดีกว่ายังไง\", \"คุณสมบัติ\", \"ผ้านุ่ม\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"fabric_comparison\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"โปรโมชัน\", \"โปรโมชั่น\", \"ส่วนลด\", \"คูปอง\", \"แฟลชเซล\"]) and not re.search(r'(?:ไม่เกิน|งบ)', raw_lower):\n",
                "        return \"promotion_discount\", (time.perf_counter() - start_t) * 1000.0\n",
                "    if any(pt in raw_lower for pt in [\"ไม่เกิน\", \"งบ\", \"บาท\", \"ขอดู\", \"หาเสื้อ\", \"ราคาประมาณ\"]):\n",
                "        return \"product_search\", (time.perf_counter() - start_t) * 1000.0\n",
                "        \n",
                "    # Tier 2.5 ChromaDB Few-Shot Search (Using CV Train Fold Collection)\n",
                "    if cv_chroma_collection:\n",
                "        query_emb = bert_model.encode(f\"query: {raw_query}\", convert_to_tensor=False).tolist()\n",
                "        results = cv_chroma_collection.query(query_embeddings=[query_emb], n_results=1)\n",
                "        if results and results.get(\"distances\") and results[\"distances\"][0]:\n",
                "            dist = results[\"distances\"][0][0]\n",
                "            similarity = 1.0 - dist\n",
                "            top_intent = results[\"metadatas\"][0][0][\"intent\"]\n",
                "            if similarity >= 0.70:\n",
                "                return top_intent, (time.perf_counter() - start_t) * 1000.0\n",
                "                \n",
                "    # Tier 3 BERT Passage Match\n",
                "    query_text = f\"query: {corrected_query}\"\n",
                "    query_embedding = bert_model.encode(query_text, convert_to_tensor=True)\n",
                "    scores = util.cos_sim(query_embedding, passage_embeddings)[0]\n",
                "    best_idx = int(scores.argmax())\n",
                "    latency = (time.perf_counter() - start_t) * 1000.0\n",
                "    return intent_classes[best_idx], latency\n",
                "\n",
                "print(\"✅ สร้างฟังก์ชันทำนายผลทั้ง 5 สถาปัตยกรรมเรียบร้อยแล้ว\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📊 Step 4: ประมวลผล 5-Fold Stratified Cross-Validation (Leak-Free Execution)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# เตรียมระบบ ChromaDB ในหน่วยความจำชั่วคราวสำหรับ Cross-Validation\n",
                "chroma_ephemeral = chromadb.Client()\n",
                "\n",
                "X = np.array([item[\"query\"] for item in ground_truth_data])\n",
                "y = np.array([item[\"expected_intent\"] for item in ground_truth_data])\n",
                "has_typo_arr = np.array([item.get(\"has_typos\", False) for item in ground_truth_data])\n",
                "\n",
                "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
                "\n",
                "method_names = [\n",
                "    \"1. Pure BERT\",\n",
                "    \"2. Edit Distance + BERT\",\n",
                "    \"3. Rules + Pure BERT\",\n",
                "    \"4a. 4-Tier Pipeline (No FewShot)\",\n",
                "    \"4b. Full 4-Tier (Leak-Free 5-Fold CV)\"\n",
                "]\n",
                "\n",
                "cv_results = {m: {\"y_true\": [], \"y_pred\": [], \"latencies\": [], \"typo_correct\": 0, \"typo_total\": 0, \"clean_correct\": 0, \"clean_total\": 0} for m in method_names}\n",
                "detailed_logs = []\n",
                "\n",
                "print(\"🚀 เริ่มการประมวลผล 5-Fold Stratified Cross-Validation (100% Data Leakage Protection)...\")\n",
                "\n",
                "for fold_idx, (train_idx, test_idx) in enumerate(skf.split(X, y)):\n",
                "    print(f\"   🔄 กำลังประมวลผล Fold {fold_idx + 1}/5 (Train: {len(train_idx)}, Test: {len(test_idx)})...\")\n",
                "    \n",
                "    # สร้าง ChromaDB Collection พิเศษเฉพาะ Train Fold สำหรับ Method 4b\n",
                "    coll_name = f\"cv_fold_{fold_idx}\"\n",
                "    try:\n",
                "        chroma_ephemeral.delete_collection(coll_name)\n",
                "    except Exception:\n",
                "        pass\n",
                "    cv_collection = chroma_ephemeral.create_collection(coll_name)\n",
                "    \n",
                "    train_docs = [f\"query: {X[i]}\" for i in train_idx]\n",
                "    train_embs = bert_model.encode(train_docs, convert_to_tensor=False).tolist()\n",
                "    train_ids = [f\"tr_{i}\" for i in train_idx]\n",
                "    train_metas = [{\"intent\": y[i], \"query\": X[i]} for i in train_idx]\n",
                "    cv_collection.add(ids=train_ids, embeddings=train_embs, metadatas=train_metas, documents=[X[i] for i in train_idx])\n",
                "    \n",
                "    # ทดสอบประมวลผลใน Test Set\n",
                "    for idx in test_idx:\n",
                "        q = X[idx]\n",
                "        expected = y[idx]\n",
                "        has_typo = has_typo_arr[idx]\n",
                "        \n",
                "        # รันทั้ง 5 วิธี\n",
                "        preds = {}\n",
                "        preds[\"1. Pure BERT\"] = predict_method_1_pure_bert(q)\n",
                "        preds[\"2. Edit Distance + BERT\"] = predict_method_2_editdistance_bert(q)\n",
                "        preds[\"3. Rules + Pure BERT\"] = predict_method_3_rules_pure_bert(q)\n",
                "        preds[\"4a. 4-Tier Pipeline (No FewShot)\"] = predict_method_4a_no_fewshot(q)\n",
                "        preds[\"4b. Full 4-Tier (Leak-Free 5-Fold CV)\"] = predict_method_4b_cv_fewshot(q, cv_collection)\n",
                "        \n",
                "        for m_name in method_names:\n",
                "            pred_intent, lat = preds[m_name]\n",
                "            is_corr = (pred_intent == expected)\n",
                "            \n",
                "            cv_results[m_name][\"y_true\"].append(expected)\n",
                "            cv_results[m_name][\"y_pred\"].append(pred_intent)\n",
                "            cv_results[m_name][\"latencies\"].append(lat)\n",
                "            \n",
                "            if has_typo:\n",
                "                cv_results[m_name][\"typo_total\"] += 1\n",
                "                if is_corr:\n",
                "                    cv_results[m_name][\"typo_correct\"] += 1\n",
                "            else:\n",
                "                cv_results[m_name][\"clean_total\"] += 1\n",
                "                if is_corr:\n",
                "                    cv_results[m_name][\"clean_correct\"] += 1\n",
                "                    \n",
                "            detailed_logs.append({\n",
                "                \"Fold\": fold_idx + 1,\n",
                "                \"Method\": m_name,\n",
                "                \"Query\": q,\n",
                "                \"Has_Typo\": has_typo,\n",
                "                \"Expected\": expected,\n",
                "                \"Predicted\": pred_intent,\n",
                "                \"Is_Correct\": is_corr,\n",
                "                \"Latency_ms\": lat\n",
                "            })\n",
                "\n",
                "print(\"✅ สำเร็จ! ประมวลผล 5-Fold Cross Validation ปราศจาก Data Leakage 100%\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🏆 Step 5: ตารางสรุปผลการวัดผลที่เที่ยงตรง (Final Fair Benchmark Results)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "summary_data = []\n",
                "for m_name in method_names:\n",
                "    data = cv_results[m_name]\n",
                "    acc = accuracy_score(data[\"y_true\"], data[\"y_pred\"]) * 100.0\n",
                "    f1 = f1_score(data[\"y_true\"], data[\"y_pred\"], average=\"macro\")\n",
                "    avg_lat = np.mean(data[\"latencies\"])\n",
                "    p95_lat = np.percentile(data[\"latencies\"], 95)\n",
                "    \n",
                "    typo_acc = (data[\"typo_correct\"] / data[\"typo_total\"] * 100.0) if data[\"typo_total\"] > 0 else 0.0\n",
                "    clean_acc = (data[\"clean_correct\"] / data[\"clean_total\"] * 100.0) if data[\"clean_total\"] > 0 else 0.0\n",
                "    \n",
                "    summary_data.append({\n",
                "        \"Architecture Method\": m_name,\n",
                "        \"Fair Accuracy (%)\": f\"{acc:.2f}%\",\n",
                "        \"Macro F1-Score\": f\"{f1:.4f}\",\n",
                "        \"Typo Queries Acc (%)\": f\"{typo_acc:.2f}% ({data['typo_correct']}/{data['typo_total']})\",\n",
                "        \"Clean Queries Acc (%)\": f\"{clean_acc:.2f}% ({data['clean_correct']}/{data['clean_total']})\",\n",
                "        \"Avg Latency (ms)\": f\"{avg_lat:.2f} ms\",\n",
                "        \"P95 Latency (ms)\": f\"{p95_lat:.2f} ms\"\n",
                "    })\n",
                "\n",
                "df_summary = pd.DataFrame(summary_data)\n",
                "from IPython.display import display\n",
                "print(\"=========================================================================================\")\n",
                "print(\"🏆 สรุปผลการทดสอบที่เที่ยงตรง (5-Fold Stratified Cross-Validation Results)\")\n",
                "print(\"=========================================================================================\")\n",
                "display(df_summary)\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔍 Step 6: วิเคราะห์การทำนายผิดพลาดเชิงลึก (Fair Misclassification Analysis)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "df_logs = pd.DataFrame(detailed_logs)\n",
                "pure_misses = df_logs[(df_logs[\"Method\"] == \"1. Pure BERT\") & (~df_logs[\"Is_Correct\"])]\n",
                "cv_4tier_misses = df_logs[(df_logs[\"Method\"] == \"4b. Full 4-Tier (Leak-Free 5-Fold CV)\") & (~df_logs[\"Is_Correct\"])]\n",
                "\n",
                "print(f\"❌ จำนวนเคสที่ Pure BERT ทำนายผิดพลาด: {len(pure_misses)} เคส\")\n",
                "if not pure_misses.empty:\n",
                "    display(pure_misses[[\"Fold\", \"Query\", \"Has_Typo\", \"Expected\", \"Predicted\", \"Latency_ms\"]].head(10))\n",
                "\n",
                "print(f\"\\n❌ จำนวนเคสที่ Full 4-Tier (Leak-Free 5-Fold CV) ทำนายผิดพลาด: {len(cv_4tier_misses)} เคส\")\n",
                "if not cv_4tier_misses.empty:\n",
                "    display(cv_4tier_misses[[\"Fold\", \"Query\", \"Has_Typo\", \"Expected\", \"Predicted\", \"Latency_ms\"]])\n"
            ]
        }
    ]
    
    notebook_content = {
        "cells": cells,
        "metadata": {
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook_content, f, ensure_ascii=False, indent=1)
        
    print(f"✅ Leak-free notebook updated successfully at {notebook_path}")

if __name__ == "__main__":
    generate_notebook()
